-- 1. Desliga a verificação de chave estrangeira
SET FOREIGN_KEY_CHECKS = 0;

-- 2. Agora o TRUNCATE funciona
TRUNCATE TABLE produto;

-- 3. Liga a verificação de novo (Muito importante!)
SET FOREIGN_KEY_CHECKS = 1;

-- 4. Insere os dados novos
INSERT INTO produto (nome, nome_cientifico, grupo, preco, estoque, url_imagem, descricao, alimentacao, habitat) VALUES 
-- === MAMÍFEROS ===
('Furão (Ferret)', 'Mustela putorius furo', 'Mamífero', 8500.00, 3, 'https://images.unsplash.com/photo-1615049539775-68045559d825', 'Animal exótico agitado, curioso e muito brincalhão. No Brasil, só é permitido se castrado e microchipado.', 'Ração super premium específica para furões (alta proteína) e petiscos de carne.', 'Gaiolas grandes com vários andares, redes e túneis. Requer tempo solto sob supervisão.'),
('Hedgehog (Ouriço Pigmeu)', 'Atelerix albiventris', 'Mamífero', 1800.00, 5, 'https://images.unsplash.com/photo-1599488615731-7e5c28a39f1c', 'Pequeno mamífero noturno coberto de espinhos. É solitário e muito fofo, ficando uma "bolinha" quando assustado.', 'Insetos (tenébrios, baratas) e ração de alta qualidade para gatos ou específica.', 'Terrário ou caixa plástica bem ventilada, com aquecimento (24-28°C) e roda de exercícios.'),
('Chinchila', 'Chinchilla lanigera', 'Mamífero', 450.00, 8, 'https://images.unsplash.com/photo-1595624132647-79888ccc0837', 'Roedor dos Andes famoso por sua pelagem extremamente macia. Tem hábitos noturnos e vive 10-20 anos.', 'Ração própria, feno à vontade e alfafa seca.', 'Gaiola vertical alta com prateleiras. Necessita de banho de pó (carbonato de cálcio) e ambiente fresco.'),
('Porquinho-da-Índia', 'Cavia porcellus', 'Mamífero', 80.00, 15, 'https://images.unsplash.com/photo-1535241556845-3a31a1913f28', 'Dócil e sociável, adora interagir e "conversar" com seus donos através de sons.', 'Feno (80% da dieta), vegetais frescos ricos em Vitamina C e ração.', 'Cercado amplo no chão (chiqueirinho) com toca e forração macia.'),
('Hamster Sírio', 'Mesocricetus auratus', 'Mamífero', 40.00, 20, 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca', 'O maior e mais comum dos hamsters. Solitário e territorial, deve viver sozinho.', 'Mix de sementes, ração extrusada e frutas ocasionais.', 'Gaiola com tubos e roda de exercício grande (min 20cm diâmetro).'),
('Hamster Anão Russo', 'Phodopus sungorus', 'Mamífero', 35.00, 18, 'https://images.unsplash.com/photo-1548767797-d8c844163c4c', 'Pequeno e veloz, possui uma listra dorsal característica. Pode viver em pares do mesmo sexo se habituados.', 'Sementes pequenas, ração específica e larvas secas.', 'Gaiola com malha fina ou terrário de vidro para evitar fugas.'),
('Gerbil (Esquilo da Mongólia)', 'Meriones unguiculatus', 'Mamífero', 30.00, 12, 'https://images.unsplash.com/photo-1591871937573-74dbba515c4c', 'Roedor do deserto muito sociável e limpo. Quase não produz cheiro na urina.', 'Ração para hamsters/gerbils e sementes.', 'Terrário com camada grossa de substrato para cavar túneis.'),
('Twister (Rato Dumbo)', 'Rattus norvegicus', 'Mamífero', 50.00, 10, 'https://images.unsplash.com/photo-1603525547631-f925b689a74a', 'Extremamente inteligente, cria laços fortes com o dono. É considerado o "cachorro" dos roedores.', 'Ração extrusada específica, frutas, legumes e ovos cozidos.', 'Gaiola alta com redes, cordas e brinquedos de inteligência.'),
('Coelho Mini Lionhead', 'Oryctolagus cuniculus', 'Mamífero', 250.00, 6, 'https://images.unsplash.com/photo-1585110396093-6e01b67f607c', 'Coelho anão com uma "juba" de leão ao redor da cabeça. Temperamento calmo.', 'Feno à vontade, folhas verdes escuras e ração limitada.', 'Cercado interno ou gaiola muito ampla. Precisa de exercícios diários.'),
('Mini Pig', 'Sus scrofa domesticus', 'Mamífero', 1500.00, 2, 'https://images.unsplash.com/photo-1516641396056-0ce60a85d49f', 'Porco de estimação selecionado para ser menor, mas ainda pode chegar a 40-60kg. Muito inteligente.', 'Ração para mini pigs, vegetais, frutas e raízes.', 'Casa com quintal. Precisa de área para fuçar e proteção contra sol forte.'),

-- === RÉPTEIS ===
('Corn Snake (Cobra do Milho)', 'Pantherophis guttatus', 'Réptil', 450.00, 10, 'https://images.unsplash.com/photo-1559214369-a6b1d7919865', 'A cobra mais popular do mundo. Dócil, colorida e fácil de manusear.', 'Roedores (camundongos) descongelados a cada 7-10 dias.', 'Terrário com aquecimento (toca quente e fria) e substrato de aspen.'),
('Píton Real (Ball Python)', 'Python regius', 'Réptil', 3500.00, 4, 'https://images.unsplash.com/photo-1615233500570-c5a47e989c79', 'Cobra robusta e calma que vira uma "bola" quando tímida. Existem centenas de cores (morphs).', 'Ratos (Rattus) descongelados.', 'Terrário com umidade controlada (60%+) e aquecimento.'),
('Jiboia BCI (Legalizada)', 'Boa constrictor imperator', 'Réptil', 4000.00, 3, 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce', 'Serpente clássica e impressionante. Animal silvestre nascido em cativeiro autorizado.', 'Roedores ou coelhos (dependendo do tamanho).', 'Terrário grande e reforçado, com galhos fortes para escalar.'),
('Jiboia Arco-Íris da Caatinga', 'Epicrates assisi', 'Réptil', 2800.00, 3, 'https://images.unsplash.com/photo-1596711684368-2e06173d1c16', 'Serpente nativa belíssima que reflete as cores do arco-íris sob a luz do sol.', 'Roedores descongelados.', 'Terrário com alta necessidade de esconderijos e temperatura estável.'),
('Leopard Gecko', 'Eublepharis macularius', 'Réptil', 1200.00, 8, 'https://images.unsplash.com/photo-1622288349271-e97c92f44760', 'Lagarto noturno do deserto, possui pálpebras (pisca) e é muito simpático.', 'Insetos vivos (grilos, baratas, tenébrios) suplementados com cálcio.', 'Terrário desértico com placa aquecida em um dos lados.'),
('Crested Gecko', 'Correlophus ciliatus', 'Réptil', 3000.00, 4, 'https://images.unsplash.com/photo-1628148902506-69537616d252', 'Lagarto arborícola que parece um dragãozinho. Salta entre galhos e adora frutas.', 'Papas de frutas específicas (Crested Diet) e insetos ocasionais.', 'Terrário vertical tropical com muitas plantas e umidade.'),
('Iguana Verde', 'Iguana iguana', 'Réptil', 2500.00, 2, 'https://images.unsplash.com/photo-1535591273668-578e31182c4f', 'Lagarto gigante herbívoro. Requer muito espaço e dedicação quando adulto.', 'Folhas verdes escuras, legumes e frutas (estritamente vegetariano).', 'Terrário gigante ou viveiro telado com lâmpadas UVB potentes.'),
('Teiú', 'Salvator merianae', 'Réptil', 2200.00, 3, 'https://images.unsplash.com/photo-1611704204423-45547477145d', 'O "cachorro" dos répteis. Pode ficar muito dócil e andar pela casa sob supervisão.', 'Onívoro: carne, ovos, frutas, insetos e ração.', 'Recinto externo ou terrário muito grande com lâmpadas de aquecimento.'),
('Dragão Barbudo (Pogona)', 'Pogona vitticeps', 'Réptil', 2500.00, 5, 'https://images.unsplash.com/photo-1555685812-4b943f1cb0eb', 'Lagarto australiano muito interativo que "acena" com a pata. Ama o calor.', 'Vegetais e insetos vivos.', 'Terrário desértico com iluminação UVB forte e alta temperatura.'),
('Jabuti-Piranga', 'Chelonoidis carbonarius', 'Réptil', 800.00, 10, 'https://images.unsplash.com/photo-1508455858334-95337ba25607', 'O quelônio mais querido do Brasil. Casco preto com manchas vermelhas/laranjas.', 'Frutas, vegetais, flores e proteína animal ocasional.', 'Jardim ou terrário aberto com acesso ao sol e área sombreada.'),
('Jabuti-Tinga', 'Chelonoidis denticulatus', 'Réptil', 1000.00, 4, 'https://images.unsplash.com/photo-1437622645530-1e39026c7317', 'Maior que o Piranga, prefere ambientes mais úmidos de floresta. Manchas amarelas.', 'Frutas, folhas e cogumelos.', 'Recinto úmido, sombreado e espaçoso.'),
('Tigre d\'água', 'Trachemys dorbigni', 'Réptil', 350.00, 12, 'https://images.unsplash.com/photo-1596765793400-98308e426615', 'Tartaruga aquática ativa. Cresce bastante e vive muitos anos.', 'Ração para tartarugas, peixes e vegetais.', 'Aquaterrário com parte seca e lâmpadas UVB/Aquecimento.'),

-- === AVES ===
('Cacatua Alba', 'Cacatua alba', 'Ave', 18000.00, 1, 'https://images.unsplash.com/photo-1605284411802-1279262f7902', 'Grande cacatua branca muito apegada e carente. Exige muita atenção do dono.', 'Ração extrusada, sementes, frutas e nozes.', 'Viveiro grande com muitos brinquedos de madeira para destruir.'),
('Cacatua Galah', 'Eolophus roseicapilla', 'Ave', 12000.00, 2, 'https://images.unsplash.com/photo-1551329388-1a5c464c1537', 'Cacatua rosa e cinza, muito bonita e um pouco mais independente que a Alba.', 'Sementes (pouca gordura), ração e vegetais.', 'Viveiro espaçoso.'),
('Papagaio do Congo', 'Psittacus erithacus', 'Ave', 16000.00, 2, 'https://images.unsplash.com/photo-1544377074-b77876a4df15', 'Considerada a ave mais inteligente do mundo. Pode falar centenas de palavras.', 'Ração extrusada de alta qualidade e frutas.', 'Gaiola grande no centro da atividade da casa. Precisa de estímulo mental.'),
('Eclectus', 'Eclectus roratus', 'Ave', 11000.00, 2, 'https://images.unsplash.com/photo-1552554278-657c00184451', 'Dimorfismo sexual extremo: Macho é verde, Fêmea é vermelha e azul.', 'Muitas frutas e vegetais frescos (dieta mais úmida que outros papagaios).', 'Viveiro espaçoso.'),
('Ring Neck', 'Psittacula krameri', 'Ave', 1200.00, 8, 'https://images.unsplash.com/photo-1588661642959-5484501a44c7', 'Periquito de colar indiano. Ótimo falador e muito independente.', 'Ração extrusada, sementes e frutas.', 'Gaiola média/grande com brinquedos.'),
('Calopsita', 'Nymphicus hollandicus', 'Ave', 250.00, 20, 'https://images.unsplash.com/photo-1517789178306-02758f8b34f2', 'A ave pet mais popular. Dócil, assobia músicas e adora carinho na cabeça.', 'Mix de sementes e ração extrusada.', 'Gaiola aberta e convívio solto pela casa.'),
('Periquito Australiano', 'Melopsittacus undulatus', 'Ave', 50.00, 25, 'https://images.unsplash.com/photo-1616428782352-8c4302213df6', 'Pequeno, colorido e tagarela. Ideal para iniciantes.', 'Sementes e vegetais.', 'Gaiola espaçosa, preferencialmente em pares.'),
('Agapornis Roseicollis', 'Agapornis roseicollis', 'Ave', 150.00, 15, 'https://images.unsplash.com/photo-1583168285906-89689408e001', 'O "Pássaro do Amor". Muito territorial mas leal ao dono.', 'Sementes e ração.', 'Gaiola média.'),
('Agapornis Personata', 'Agapornis personatus', 'Ave', 180.00, 10, 'https://images.unsplash.com/photo-1535446071477-987829705a1e', 'Conhecido pela "máscara" preta na cabeça. Cores vibrantes.', 'Sementes e ração.', 'Gaiola média.'),
('Agapornis Fischeri', 'Agapornis fischeri', 'Ave', 180.00, 10, 'https://images.unsplash.com/photo-1543501758-a5b4c9356d78', 'Parecido com o Roseicollis mas com anel branco ao redor dos olhos.', 'Sementes e ração.', 'Gaiola média.'),
('Canário Belga', 'Serinus canaria', 'Ave', 100.00, 15, 'https://images.unsplash.com/photo-1596798008855-520e50942557', 'Mestre do canto. Existem diversas cores e tipos de plumagem.', 'Alpiste, colza e farinhada.', 'Gaiola retangular para voo horizontal.'),
('Diamante de Gould', 'Erythrura gouldiae', 'Ave', 350.00, 6, 'https://images.unsplash.com/photo-1555543787-84615a995727', 'Uma das aves mais coloridas do mundo. Tímido e sensível.', 'Sementes pequenas (painço) e farinhada.', 'Viveiro calmo sem correntes de ar.'),
('Diamante Mandarim', 'Taeniopygia guttata', 'Ave', 60.00, 12, 'https://images.unsplash.com/photo-1549419225-b44c69399426', 'Zebra Finch. Pequeno, ativo e emite sons parecidos com brinquedos de corda.', 'Sementes exóticas.', 'Gaiola em grupos.'),
('Manon', 'Lonchura striata domestica', 'Ave', 40.00, 15, 'https://images.unsplash.com/photo-1610486796263-d2d473489370', 'Excelente pai adotivo para outras aves. Muito sociável e pacífico.', 'Sementes.', 'Gaiola em colônias.'),
('Calafate', 'Lonchura oryzivora', 'Ave', 120.00, 8, 'https://images.unsplash.com/photo-1595508821945-8f742416f406', 'Pássaro Java Sparrow. Bico robusto e canto suave.', 'Sementes e arroz com casca.', 'Gaiola espaçosa.'),
('Rosela', 'Platycercus eximius', 'Ave', 1500.00, 4, 'https://images.unsplash.com/photo-1618395535316-2495d4d38515', 'Ave australiana de plumagem deslumbrante. Menos dócil ao toque, mais ornamental.', 'Sementes, frutas e insetos.', 'Viveiro grande para voo.'),
('Red Rumped', 'Psephotus haematonotus', 'Ave', 300.00, 6, 'https://images.unsplash.com/photo-1620696342898-050965c27635', 'Periquito de dorso vermelho. Canto melódico agradável.', 'Sementes e vegetais.', 'Gaiola média.'),
('Arara Canindé (Legalizada)', 'Ara ararauna', 'Ave', 10000.00, 2, 'https://images.unsplash.com/photo-1543167812-32b05b5f891b', 'Símbolo do Brasil. Grande, barulhenta e exige espaço enorme.', 'Nozes, sementes grandes, frutas e ração.', 'Viveiro gigante ou área de voo livre supervisionada.');